package com.cokkiri.secondhand.global.exception;

public enum CustomExceptionType {

	// JWT Token
	ILLEGAL_JWT_TOKEN_EXCEPTION,
	NOT_EXIST_ACCESS_TOKEN_EXCEPTION,
	NOT_EXIST_REFRESH_TOKEN_EXCEPTION,

	// User
	LOGIN_FAILURE_EXCEPTION,
	NICKNAME_DUPLICATION_EXCEPTION,
	USERNAME_DUPLICATION_EXCEPTION,

	// Location
	NOT_FOUND_LOCATION_EXCEPTION,

	// Status
	ILLEGAL_STATUS_EXCEPTION;
}
