package com.cokkiri.secondhand.global.exception;

public enum CustomExceptionType {

	// JWT Token
	ILLEGAL_JWT_TOKEN_EXCEPTION,
	NOT_EXIST_ACCESS_TOKEN_EXCEPTION,
	NOT_EXIST_REFRESH_TOKEN_EXCEPTION,

	// Item
	NOT_FOUND_ITEM_EXCEPTION,

	// User
	LOGIN_FAILURE_EXCEPTION,
	NICKNAME_DUPLICATION_EXCEPTION,
	USERNAME_DUPLICATION_EXCEPTION,
	NOT_FOUND_USER_EXCEPTION,

	// Location
	NOT_FOUND_LOCATION_EXCEPTION,

	// MyLocation
	DUPLICATE_MY_LOCATION_EXCEPTION,
	LIMIT_EXCEEDED_MY_LOCATION_EXCEPTION,
	NOT_FOUND_MY_LOCATION_EXCEPTION,
	MY_LOCATION_DELETION_NOT_ALLOWED_EXCEPTION,
	EMPTY_MY_LOCATION_LIST_EXCEPTION,
	NOT_EXIST_SELECTED_MY_LOCATION_EXCEPTION,

	// Status
	ILLEGAL_STATUS_EXCEPTION;
}
