name: second-hand auto-deploy

on:
  pull_request:
    branches: [ "fe" ]

permissions:
  contents: read

jobs:

  fe-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Source 단계
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 2. 환경 변수 파일 생성
      - name: Set .env file
        run: |
          touch ./.env
          echo '${{ secrets.APE_ENV_FILE }}' > ./.env

      # 3. docker hub로 build & push
      - name: Docker Build and Push
        run: |
          docker login -u ${{ secrets.APE_DOCKER_USERNAME }} -p ${{ secrets.APE_DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.APE_DOCKER_USERNAME }}/second-hand-web-with-nginx:latest .
          docker push ${{ secrets.APE_DOCKER_USERNAME }}/second-hand-web-with-nginx:latest

  SSH-Transfer:
    runs-on: ubuntu-latest
    steps:

      - name: SSH Transfer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APE_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.APE_EC2_PRIVATE_KEY }}
          script: |
            sudo docker-compose down -v
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.APE_DOCKER_USERNAME }}/second-hand-web-with-nginx:latest
            sudo docker-compose up -d
            sudo docker image prune -a -f